In [3]:
from cvxopt import matrix
from cvxopt.solvers import qp
import numpy as np

In [4]:
n = 4
Cov = matrix([[0.076900,0.039968,0.018111,-0.000288],
              [0.039968,0.050244,0.019033,-0.000060],
              [0.018111,0.019033,0.021381,0.007511],
              [-0.000288,-0.000060,0.007511,0.008542]])
print(Cov)
Mean = matrix([0.0073,0.0346,0.0444,0.0271])
r_min = 0.035

[ 7.69e-02  4.00e-02  1.81e-02 -2.88e-04]
[ 4.00e-02  5.02e-02  1.90e-02 -6.00e-05]
[ 1.81e-02  1.90e-02  2.14e-02  7.51e-03]
[-2.88e-04 -6.00e-05  7.51e-03  8.54e-03]


In [5]:
G = matrix(np.concatenate((-np.transpose(Mean), -np.identity(n)), 0))
h = matrix(np.concatenate((-np.ones((1,1))*r_min, np.zeros((n,1))), 0))

In [6]:
A = matrix(1.0, (1,n))
b = matrix(1.0)
q = matrix(np.zeros((n,1)))
sol = qp(Cov, q, G, h, A ,b)
print(sol['x'])

     pcost       dcost       gap    pres   dres
 0:  9.6979e-03 -9.9747e-01  6e+00  2e+00  3e+00
 1:  9.7719e-03 -6.4156e-01  7e-01  4e-02  4e-02
 2:  9.2936e-03 -2.0327e-01  2e-01  1e-02  1e-02
 3:  8.7597e-03 -5.4022e-02  7e-02  1e-03  1e-03
 4:  8.2687e-03  2.5228e-03  6e-03  1e-04  1e-04
 5:  5.7185e-03  4.1849e-03  2e-03  2e-16  1e-17
 6:  5.3588e-03  5.2547e-03  1e-04  2e-16  1e-17
 7:  5.3134e-03  5.3091e-03  4e-06  1e-16  4e-17
 8:  5.3124e-03  5.3123e-03  5e-08  1e-16  3e-16
Optimal solution found.
[ 8.47e-07]
[ 4.33e-02]
[ 4.38e-01]
[ 5.19e-01]


In [14]:
print(G) 

[-7.30e-03 -3.46e-02 -4.44e-02 -2.71e-02]
[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]


In [22]:
print(h)

[-3.50e-02]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]


In [19]:
np.zeros((n,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [21]:
print(matrix(1.0, (1,n)))

[ 1.00e+00  1.00e+00  1.00e+00  1.00e+00]


In [25]:
print(q)

[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]


In [26]:
np.identity(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])